apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xzct2yj9i-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xzct2yj9i-java-quarkus-gitops